### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by uygarbayar** [master/ejabberd#3]
Can you put example of a ejabberd.cfg with mongo changes. We cant figure it out how.

**Comment by master** [comment]
{odbc_server, {mongo, "db.montague.lit", "ejabberd", "", ""}}.

Or on a per-host basis:

{host_config, "montague.lit", [ {odbc_server, {mongo, "db.montague.lit", "ejabberd", "", ""}} ]}.
{host_config, "capulet.lit", [ {odbc_server, {mysql, "db.capulet.lit", "ejabberd", "ejabberd", "v3rOnA"}} ]}.

Requires MongoSQL and eMongo driver.
